import numpy as np 

#1 Calculate total revenue generated by two product category in store 

cate1_rev = np.array([500,600,700,550])
cate2_rev = np.array([450,700,800,600])
sum1 = np.sum(cate1_rev)
sum2 = np.sum(cate2_rev)
totalSum = sum1 + sum2
print("Total sum is : " ,totalSum)


# 2 Calculate profit made by category 

rev = np.array([10000,12000,11000,10500])
expenses = np.array([4000,5000,4500,4800])
profit = rev - expenses
print("Profit of each category" , profit)
totalProfit = np.sum(profit)
print("total profit" , totalProfit)


# 3 Determine the product in store are out of stock

inventory = np.array([10,0,50,20,0])
out_of_stock = inventory == 0
print("Products out of stock:", out_of_stock)


# 4 Total cost of items in shopping cart considering the quantity and price

quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
total_cost_per_item = quantity * price_per_item
total_cost = np.sum(total_cost_per_item)
print("Total cost for each item:", total_cost_per_item)
print("Total cost of the shopping cart:", total_cost)